### ISSUE TITLE
Connected Field Date Bug

### ISSUE THREAD

**Issue by jamesduncan** [digi-serve/ab_platform_web#508]
**Describe the bug**
When you save a record and it has a connected record that contains a date field the date is being set back a single day each time you save.

https://github.com/digi-serve/ab_platform_web/assets/106924/d41d81ec-8ccd-41fb-b3fe-b8415f3242e0

**Server**
Design.DigiServe.org

**Comment by nh758** [comment]
> Not sure what labels are the right ones for this bug...feel free to change.

We don' t really use issue labels in our current workflow, so you can put whatever you want. FYI: `major`, `minor`, and `patch` are used on pull requests for release creation.

**Comment by joshAppDev** [comment]
AppBuilder is not my area, so I'm not sure how relevant this is. But there was a similar off-by-one date issue with the HR Update app in Framework7 some time back. Turned out to be a timezone issue.

When we set a date value using a 'yyyy-mm-dd' string, it would be converted into a JavaScript Date object. But JavaScript does this using the UTC timezone. So depending on the timezone of the person using the app, the day might be off by one compared to UTC.

The fix I used there was to convert the 'yyyy-mm-dd' string manually so we can control the timezone.
```js
/**
 * Takes a yyyy-mm-dd string and converts it into a Date object based on the
 * local timezone.
 *
 * This fixes an issue where the date becomes off by one day due to timezone
 * mismatch.
 *
 * @param {string} ymd
 * @return {Date}
 */
function localDate(ymd) {
   let dateUTC = new Date(ymd);
   let dateLocal = new Date(
      dateUTC.getTime() + dateUTC.getTimezoneOffset() * 60 * 1000
   );
   return dateLocal;
}

// Then later, when we set the date in the calendar widget:
calendar.setValue(localDate( MY_DATE_VALUE ));

```

Again, this was for Framework7. There might be a better solution with AppBuilder.

Just FYI, to whoever ends up working on this one.

**Comment by jamesduncan** [comment]
Prin and I discovered that this is really a bug with the Record Rules when you tell a connected record to update. We will create a new issue that clearly states the issue. It is not urgent however because the Record Rule in this case was not needed and the production issue is fixed by deleting it.
